apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rh-ws-catalog
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Workshops
  image: quay.io/aletia/rh-ws-catalog:4.14
  publisher: David Martin
  sourceType: grpc