apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rhbk-db
spec:
  serviceName: rhbk-db-service
  selector:
    matchLabels:
      app: rhbk-db
  replicas: 1
  template:
    metadata:
      labels:
        app: rhbk-db
    spec:
      containers:
        - name: rhbk-db
          image: quay.io/aletiasolucionesit/postgresql-15
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: db-data-volume
          env:
            - name: POSTGRESQL_PASSWORD
              value: rhbkdbpassword
            - name: POSTGRESQL_USER
              value: rhbkdbuser
            - name: POSTGRESQL_DATABASE
              value: rhbk
  volumeClaimTemplates:
    - metadata:
        name: db-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rhbk-db
spec:
  selector:
    app: rhbk-db
  ports:
  - port: 5432
    targetPort: 5432
