apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: rhbk
  name: rhbk
  namespace: rhbk
spec:
  db:
    database: rhbk
    host: rhbk-db
    passwordSecret:
      key: password
      name: rhbk-db-secret
    port: 5432
    usernameSecret:
      key: username
      name: rhbk-db-secret
    vendor: postgres
  hostname:
    hostname: rhbk-rhbk.apps.ocp4.example.com
  http:
    tlsSecret: rhbk-tls-secret
  instances: 1