FROM quay.io/aletiasolucionesit/keycloak-rhel9:v26 as builder

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
ADD --chown=keycloak:keycloak dasniko.keycloak-flintstones-userprovider.jar /opt/keycloak/providers/dasniko.keycloak-flintstones-userprovider.jar
RUN /opt/keycloak/bin/kc.sh build --health-enabled=true --metrics-enabled=true

FROM quay.io/aletiasolucionesit/keycloak-rhel9:v26
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://rhbk-db:5432/rhbk
ENV KC_DB_USERNAME=rhbkdbuser
ENV KC_DB_PASSWORD=rhbkdbpassword
ENV KC_HOSTNAME=rhbk-rhbk.apps.ocp4.example.com

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
