FROM quay.io/aletia/keycloak-rhel9@sha256:efc6ba8cf51353f321d3c8dec7c78dc00b413712f218a57606508d53838bf28d as builder

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
ADD --chown=keycloak:keycloak dasniko.keycloak-demo-user-spi.jar /opt/keycloak/providers/dasniko.keycloak-demo-user-spi.jar
RUN /opt/keycloak/bin/kc.sh build --health-enabled=true

FROM quay.io/aletia/keycloak-rhel9@sha256:efc6ba8cf51353f321d3c8dec7c78dc00b413712f218a57606508d53838bf28d
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://rhbk-db:5432/rhbk
ENV KC_DB_USERNAME=rhbkdbuser
ENV KC_DB_PASSWORD=rhbkdbpassword
ENV KC_HOSTNAME=rhbk-rhbk.apps.ocp4.example.com

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
